### ISSUE TITLE
Attribution missing

### ISSUE THREAD

**Issue by shreevatsa** [xmonader/letsbuildacompiler-pretty#1]
Thanks for this prettified version!

Right now, if I visit https://xmonader.github.io/letsbuildacompiler-pretty/ there is nothing explaining that this is by Jack Crenshaw. Could you please add a cover page linking to https://compilers.iecc.com/crenshaw/ and mentioning the author and dates?

Similarly for each of the individual pages, e.g. comparing https://xmonader.github.io/letsbuildacompiler-pretty/tutor02_expressionparsing.html with the original https://compilers.iecc.com/crenshaw/tutor2.txt one finds that the title “Part II: EXPRESSION PARSING”, the author “Jack W. Crenshaw, Ph.D.”, the date “24 July 1988” and the copyright notice are all missing. Could you add them back?

Otherwise, thanks for this prettification; the flowing text instead of hardcoded line-breaks is nicer, and the code samples are easier to read with the syntax highlighting.

**Comment by xmonader** [comment]
Thanks. I'm glad you liked it!

I created about page https://xmonader.github.io/letsbuildacompiler-pretty/about.html and updated the sources with titles and the dates. Not sure about the copyright notice it looks bit ugly. I added an entry about it in the about page https://xmonader.github.io/letsbuildacompiler-pretty/about.html 

Tell me what you think

**Comment by shreevatsa** [comment]
This looks good, thanks! Yes I agree it's probably not necessary to have the copyright notice on each of the individual pages; having it on the main page and having every page link to it should be enough.
