### ISSUE TITLE
Part 9 is empty

### ISSUE THREAD

**Issue by shreevatsa** [xmonader/letsbuildacompiler-pretty#2]
Right now, clicking on Part 9 (https://xmonader.github.io/letsbuildacompiler-pretty/tutor09_atopview..html) shows a blank page. (This may have something to do with the extra `.` in the name compared to the others.)

**Comment by xmonader** [comment]
Thanks for reporting this. Fixed https://xmonader.github.io/letsbuildacompiler-pretty/tutor09_atopview.html
